### 如何创建一个Tensor

#### 创建一个张量

In [2]:
import tensorflow as tf
a = tf.constant([1, 5], dtype=tf.float64)
print(a)

tf.Tensor([1. 5.], shape=(2,), dtype=float64)


In [3]:
print(a.dtype)
print(a.shape)

<dtype: 'float64'>
(2,)


#### 将numpy的数据类型转换为Tensor数据类型

In [4]:
import tensorflow as tf
import numpy as np
a = np.arange(0, 5)
b = tf.convert_to_tensor(a, dtype=tf.float64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float64)


#### 创建全为0的张量

In [5]:
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#### 创建全为0的张量

In [6]:
tf.ones([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

#### 

In [8]:
tf.fill([3, 3], 2.)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

#### 生成正态分布的随机数，默认均值为0，标准差为1

In [9]:
tf.random.normal([3,3], mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.66452384,  1.629149  , -1.3542832 ],
       [ 0.3646591 ,  1.3365703 , -1.1102356 ],
       [ 1.6498319 ,  0.03424739,  0.7851237 ]], dtype=float32)>

In [10]:
tf.random.truncated_normal([3, 3], mean=0, stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.0175891 ,  1.0895882 ,  1.4799517 ],
       [-1.9839251 ,  0.683477  ,  0.36212882],
       [-0.12068409, -1.3882682 ,  1.6050584 ]], dtype=float32)>

#### 生成均匀分布随机数 [ minval, maxval )

In [11]:
tf.random.uniform([3, 3], minval=0, maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.3914349 , 0.5467677 , 0.9109124 ],
       [0.39775026, 0.2379682 , 0.74841726],
       [0.64396274, 0.8127159 , 0.04406559]], dtype=float32)>

### 常用函

#### 强制tensor转换为该数据类型

In [12]:
x1 = tf.constant([1., 2., 3.], dtype=tf.float64)
x2 = tf.cast(x1, dtype=tf.float32)
print(x2)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [13]:
print(tf.reduce_min(x1))

tf.Tensor(1.0, shape=(), dtype=float64)


In [15]:
print(tf.reduce_max(x1))

tf.Tensor(3.0, shape=(), dtype=float64)


#### 理解axis

In [16]:
x = tf.constant([[1,2,3],
                 [2,2,3]])
print(x)

tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)


##### 计算张量沿着指定维度的平均值

In [17]:
print(tf.reduce_mean(x))

tf.Tensor(2, shape=(), dtype=int32)


In [18]:
print(tf.reduce_mean(x, axis=0))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [19]:
print(tf.reduce_mean(x, axis=1))

tf.Tensor([2 2], shape=(2,), dtype=int32)


##### 计算张量沿着指定维度的和

In [20]:
print(tf.reduce_sum(x))

tf.Tensor(13, shape=(), dtype=int32)


In [21]:
print(tf.reduce_sum(x, axis=0))

tf.Tensor([3 4 6], shape=(3,), dtype=int32)


In [22]:
print(tf.reduce_sum(x, axis=1))

tf.Tensor([6 7], shape=(2,), dtype=int32)


#### tf.Variable()
tf.Variable () 将变量标记为“可训练”，被标记的变量会在反向传播
中记录梯度信息。神经网络训练中，常用该函数标记待训练参数。

In [23]:
w = tf.Variable(tf.random.normal([2,2], mean=0, stddev=1))
w

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.26317886, 0.23720051],
       [1.4007394 , 0.93338764]], dtype=float32)>

#### TensorFlow中的数学运算

- 对应元素的四则运算：tf.add，tf.subtract，tf.multiply，tf.divide
- 平方、次方与开方： tf.square，tf.pow，tf.sqrt
- 矩阵乘：tf.matmul

#### 对应元素的四则运算

In [25]:
a = tf.ones([1, 3])
b = tf.fill([1,3],3.)

In [26]:
print(a)
print(b)

tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)
tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)


In [27]:
print(tf.add(a, b))

tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)


In [28]:
print(tf.subtract(a, b))

tf.Tensor([[-2. -2. -2.]], shape=(1, 3), dtype=float32)


In [29]:
print(tf.multiply(a, b))

tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)


In [30]:
print(tf.divide(a, b))

tf.Tensor([[0.33333334 0.33333334 0.33333334]], shape=(1, 3), dtype=float32)


#### 平方、次方与开方

In [33]:
a = tf.fill([1, 2], value=3.0)
print(a)

tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)


In [34]:
print(tf.pow(a, 3))

tf.Tensor([[27. 27.]], shape=(1, 2), dtype=float32)


In [35]:
print(tf.square(a))

tf.Tensor([[9. 9.]], shape=(1, 2), dtype=float32)


In [36]:
print(tf.sqrt(a))

tf.Tensor([[1.7320508 1.7320508]], shape=(1, 2), dtype=float32)


#### 矩阵乘 tf.matmul

In [40]:
a = tf.ones([3, 2])
b = tf.fill([2, 3], value=3.)
print(tf.matmul(a, b))

tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float32)


#### tf.data.Dataset.from_tensor_slices

切分传入张量的第一维度，生成输入特征/标签对，构建数据集
data = tf.data.Dataset.from_tensor_slices((输入特征, 标签))

In [44]:
features = tf.constant([12,23,10,17])
labels = tf.constant([0, 1, 1, 0])
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
print(dataset)

<_TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>


In [45]:
for element in dataset:
    print(element)

(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


#### tf.GradientTape

with结构记录计算过程，gradient求出张量

In [47]:
with tf.GradientTape() as tape:
    w = tf.Variable(tf.constant(3.0))
    loss = tf.pow(w, 2)

    grad = tape.gradient(loss, w)
    print(grad) 

tf.Tensor(6.0, shape=(), dtype=float32)


#### enumerate

enumerate是python的内建函数，它可遍历每个元素(如列表、元组
或字符串)，组合为：索引 元素，常在for循环中使用。

In [48]:
seq = ['one', 'two', 'three']
for i, element in enumerate(seq):
    print(i, element)

0 one
1 two
2 three


#### tf.one_hot

独热编码（one-hot encoding）：在分类问题中，常用独热码做标签，
标记类别：1表示是，0表示非。

In [50]:
classes = 3
labels = tf.constant([1, 0, 2])
output = tf.one_hot(labels, depth=classes)
print(output)

tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


#### tf.nn.softmax

当n分类的n个输出 （y0 ，y1, …… yn-1）通过softmax( ) 函数，便符合概率分布了。

In [51]:
y = tf.constant([1.01, 2.01, -0.66])
y_pro = tf.nn.softmax(y)
print("after softmax y_pro is", y_pro)
                

after softmax y_pro is tf.Tensor([0.25598174 0.69583046 0.04818781], shape=(3,), dtype=float32)


#### assign_sub

赋值操作，更新参数的值并返回。
w.assign_sub (w要自减的内容)
调用assign_sub前，先用 tf.Variable 定义变量 w 为可训练（可自更新）。

In [52]:
w = tf.Variable(4)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


#### tf.argmax

返回张量沿指定维度最大值的索引 tf.argmax (张量名,axis=操作轴)

In [54]:
import numpy as np

test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])
print(test)
# print( tf.argmax (test, axis=0)) # 返回每一列（经度）最大值的索引      

[[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]


In [55]:
print(tf.argmax(test, axis=0))

tf.Tensor([3 3 1], shape=(3,), dtype=int64)


In [56]:
print(tf.argmax(test, axis=1))

tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)


### 神经网络实现鸢尾花分类

In [2]:
#数据集读入
from sklearn.datasets import datasets


ImportError: cannot import name 'datasets' from 'sklearn.datasets' (/Users/yangbaiyinnamula/opt/anaconda3/envs/netsun/lib/python3.9/site-packages/sklearn/datasets/__init__.py)